name: tweter
description: Like Twitter but bad

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  tuple: ^2.0.0
  flutter_login: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter:

  uses-material-design: true

  assets:
    - assets/cover.png
    - assets/transparent_cover.png
    - assets/profile.png
    - assets/transparent_profile.png
    - assets/default.png
    - assets/bird.png
    - assets/fillbird.png
    - assets/fillbird.svg
